### ISSUE TITLE
[BUG - FRENCH KEYBOARDS] some letters and signs are cumbersome to type if the digit selection is enabled

### ISSUE THREAD

**Issue by benintech** [bartekplus/FluentTyper#10]
On the french keyboard, there are accented characters on the digit row : « é » on 2, « è » on 7, « ç » on 9 and « à » on 0.

Let's say for example I want to type « Par conséquent » :
![par-consequent](https://user-images.githubusercontent.com/5140169/183685766-baba60b3-cd13-463a-94aa-c9ab652ab00e.png)
At this stage, if I type « é » it selects the proposition n°2 instead :
![par-consensus](https://user-images.githubusercontent.com/5140169/183685953-81f87cf3-3898-4e38-939d-d4cb20f2ad36.png)

Another example, in English, and without accents. Let's say I want to type a filesystem path, for example /opt/local-firefox :
![local-firefox](https://user-images.githubusercontent.com/5140169/183686896-3d5c417c-da1a-4953-815b-5deb929256e5.png)
At this stage, when I type the dash, it selects the proposition n°8 instead :
![localize](https://user-images.githubusercontent.com/5140169/183686735-5108d44d-82d2-4cd2-9cde-81a7bfbaa2b5.png)

A few ideas to solve this, without disabling the digit selection alltogether
- Add an option to disable the digit selection on the regular keyboard, while enabling it on the numeric keypad. At least it will allow this option to be used on a keyboard with a numpad
- Add an option to choose a modifier key to select a digit (for example \<Ctrl\>\<Shift\>\<digit\>, or something like that). Could be useful to enable this feature on keyboards without numpads.

As it is now, the digit selection option is a little bit cumbersome to use on French keyboards, but it's still doable : I have to type \<Esc\> to close FT before typing a key on the digit row (like ampersand, single and double quotes, opening parenthesis, dash, underscore, and of course the 4 accentuated French characters previously mentioned).

**Comment by bartekplus** [comment]
There is no way to reailable detect keyboard layout across all browser(at least i'm not aware), so making it work only on keyboards with numpad is not an option. I will try to improve situation to checking the even.key which is a printable character instead of event.code which is physical key on the keyboard. That should improve situation for you.

**Comment by benintech** [comment]
> so making it work only on keyboards with numpad is not an option

Another idea would be to make it always work on numpads **too**. That shouldn't cause much of a problem on keyboards without numpad, no ?

**Comment by bartekplus** [comment]
It will now work rely on key instead of hardware key code, so yes it should now work only when you type "numer" without checking key code. Feel free to test new release and let me know what you think.

**Comment by benintech** [comment]
Works fine on French keyboards now (AZERTY), through the numpad. THANKS

Please note however that it doesn't work on French keyboards without numpad, because you'd have to type \<Shift\>\<digit\> to get to the number, and FT's suggestions are closed when you type \<Shift\>. Not a problem for me though, I almost always have a numpad, but I just wanted to let you know.
