### ISSUE TITLE
Every non-letter character should be considered as a word separator

### ISSUE THREAD

**Issue by benintech** [bartekplus/FluentTyper#11]
I just tested a few special characters, that all seem to be accounted for as letters : {, (, [, *, -, +,  <, and so on. I think only letters should be accounted for as, well, letters, and every other character should be considered as a word separator. In some cases the suggestions are annoying and it would be better if they weren't displayed at all. In each of the following screenshots, IMO no suggestion at all should be displayed. For those screenshots, my word length setting is 5.

Note : that example comes from a wiki that I use, in which sometimes I need to switch to the source to type some things in wiki syntax, or to include macros, like in that example where I include an {html} macro :
![html1](https://user-images.githubusercontent.com/5140169/183822429-65a7ea0c-2172-446f-b55a-2542d9d8eddf.png)![html2](https://user-images.githubusercontent.com/5140169/183822452-738ffd32-a652-4f3f-8adc-e1ae33804a0e.png)![html3](https://user-images.githubusercontent.com/5140169/183822457-a87ffa2e-81a1-4821-aaf7-991a751d0b82.png)![html4](https://user-images.githubusercontent.com/5140169/183822465-a88488d4-2e6a-4ca5-a9a0-f44ab259b7e4.png)![html5](https://user-images.githubusercontent.com/5140169/183822475-2e082625-c013-4bac-985f-3ac52a84d2e6.png)

If non-letters were all treated as word separators, none of those suggestions would have popped up.

[EDIT] There may be one exception to this rule. In French a lots of words contain a dash (« après-midi » for example, which means « afternoon »), so a dash shouldn't be considered as a word separator. To my knowledge there's no other special character that could be part of a word, at least not in the languages I know.

**Comment by bartekplus** [comment]
Hey,

I'll exclude all special characters when counting word length used to trigger prediction.

When it comes to use all special characters as word separator I wouldn't like to change that. In the past FF treated all special characters as  word separators, but this mode was too aggressive.  FF keeps suggesting words to the point it was getting annoying. You also noticed that, and if I treat all special characters as word separator it will just become worse.
It was requested by few uses to change that and currently FF will display suggestion only if word includes any of " [ ( { < / - * + = ", almost all other special chars will be ignored and FF won't display any suggestions.

**Comment by benintech** [comment]
OK I'll test it as soon as you upload it on FF

Note : I tried to install it from GitHub, but didn't succeed.
I successfully managed to make the archive using web-ext, and I disabled xpinstall.signatures.required in about:config, but I still get the following message :
![add-on-unverified](https://user-images.githubusercontent.com/5140169/184335567-889ff31b-9bcf-47cd-a689-742b2307161e.png)

I think add-ons from GitHub can not be tested on a regular FF installation, only ESR, Developer or Nightly allow the installation of unsigned add-ons (https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox). Is that the case, or am I missing something ?

**Comment by bartekplus** [comment]
It should work just fine. In the addon menu chose "debug add-ons" then "load temporary add-on"

**Comment by benintech** [comment]
> It should work just fine. In the addon menu chose "debug add-ons" then "load temporary add-on"

:+1: 
Thanks, it worked. I knew I was missing something !

**Comment by benintech** [comment]
> I'll exclude all special characters when counting word length used to trigger prediction.
:+1:  just tested, much better now

> ... currently FF will display suggestion only if word includes any of " [ ( { < / - * + = ", almost all other special chars will be ignored and FF won't display any suggestions.

OK. Please note that I just tested and noticed that the single quote is also part of that list (which is a good thing, IMO).

I think you should also add the double quotes to the list, words between double quotes are quite common (e.g., id="something").
