### ISSUE TITLE
FluentTyper not working in google docs

### ISSUE THREAD

**Issue by heather-hev** [bartekplus/FluentTyper#110]
FluentTyper is not currently working in google docs. This was first noticed on a Chromebook- the person found that FluentTyper would generate the suggestions in the box for the title of the document, but not in the full document itself. I tried on my own computer (Surface Pro 6, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz, on chrome browser with extension installed) and found the same thing. Typing into the 'try it out' section of the extension's settings works fine. I checked the reviews and saw that some others were having the same issues.

**Comment by bartekplus** [comment]
It's a known limitation -> https://github.com/bartekplus/FluentTyper/issues/47#issue-1687125620
