### ISSUE TITLE
Add autocorrect functionality

### ISSUE THREAD

**Issue by ericpa06** [bartekplus/FluentTyper#12]
Hi, I just bumped with your project while browning autocorrect extensions on Firefox site, first of all it's pretty well done, probably the best swiftkey-like application on the browner domain. Secondly, I would like to suggest some features if I may:

I think the autocorrect aspect should be implemented, like, I played a little bit with the extension and it would be interesting if you could have the software to autocorrect things for you based on a list of words automatically. Like, for instance:

If you type "4you" and then you pressed "space" or dot or pressed the enter key, signalizing you finished the sentence, the script would automatically replace with "For you".

Maybe it's not the direction that you want to the project on, but if you interested, I would advise to look on PhraseExpress, it's meanly an autocorrect application but it has several features that it would be interested if they were implemented in your add-on.
![image](https://user-images.githubusercontent.com/6937720/184190718-bfb99f5e-8e54-43de-8793-3c09a065fb00.png)

**Comment by bartekplus** [comment]
Well there is something like that implemented. But this mode is very aggressive and rather annoying (and there are some bugs with reverting autocorrect with Backspace). You can enable "Auto complete word on space" in FF options.

Please note this use dictionary, ngram prediction and text expander phrases.  If you are looking for a tool that do that only for user provided list, I think there are better choices

**Comment by benintech** [comment]
> If you type "4you" and then you pressed "space" or dot or pressed the enter key, signalizing you finished the sentence, the script would automatically replace with "For you".

Also note that you already have the "Text Expander" tab in the settings, where you can define your set of abbreviations :
![4you](https://user-images.githubusercontent.com/5140169/184377750-e54891d7-73bc-416e-b1d8-bf6cb1b0549a.png)
