### ISSUE TITLE
Doesn't appear to be any way to add websites to the domain blacklist

### ISSUE THREAD

**Issue by s-i-m-s** [bartekplus/FluentTyper#20]
Maybe i'm missing something obvious but there is an input box on the domain blacklist page, you can select the box but can't enter anything.

**Comment by bartosztomczyk** [comment]
At the moment the only way to add something to block list is to click on FF icon and toggle "Enable autocomplete on:
 <URL>"

![image](https://user-images.githubusercontent.com/110402905/187485092-b6eb6b41-ce98-432c-a7ee-23786dee3528.png)

**Comment by bartekplus** [comment]
At the moment the only way to add something to block list is to click on FF icon and toggle "Enable autocomplete on:
 < URL>"
I think is more convenient to click then type an url, but I might consider to add that in options.

![image](https://user-images.githubusercontent.com/7108667/187485727-578f3a44-2235-446e-a9f8-24c2ec185ac9.png)

**Comment by s-i-m-s** [comment]
See that's simple and should have been obvious yet I still managed to miss it.
