### ISSUE TITLE
Add support for Greek language 

### ISSUE THREAD

**Issue by siomosp** [bartekplus/FluentTyper#26]
Hello,
it is possible to add support for Greek language?

**Comment by bartekplus** [comment]
The basics support based on Greek dictionary is fairy simple to do. The issue is to get good corpus database/Greek sentences database/n grams. Without good database FluentTyper will have limited functionality. Are you aware if there are any free Greek corpus database that can be used?

**Comment by siomosp** [comment]
I will try to find it.  What database format is needed?

**Comment by bartekplus** [comment]
List of sentences - one sentence per line would be great.
the 3-ngrams ( 4,5 ngrams would also be good). Eg: word1 word2 word3 frequency_count

Please note that prediction quality depends on that. So while dump from eg. Wikipedia could be done it's might be not ideal as it's using very formal language. So the database must be representative and mix of different sources.

**Comment by siomosp** [comment]
Maybe this is helpful?
https://github.com/nlpaueb/gr-nlp-toolkit
(I don't have the knowledge to help more, i'm sorry!)

**Comment by bartekplus** [comment]
I've added basic Greek support(only dictionary based prediction) it will be available in 2022.12.31 version. There is no n-gram perdition since I didn't find database that can be easily used.
