### ISSUE TITLE
[French] A lot of irrelevant words are proposed

### ISSUE THREAD

**Issue by benintech** [bartekplus/FluentTyper#3]
Let's say I want to write "Cette boisson est absolument délicieuse".

- None of these words start with « boiss », yet they are proposed :
![boisson-1](https://user-images.githubusercontent.com/5140169/182411877-d9e47362-ded0-48f7-ad08-fc20b198b3ea.png)

- With « boisso » it shows the right word, but only at the second place, the first one shouldn't be a candidate (« boiss**e** »)
![boisson-2](https://user-images.githubusercontent.com/5140169/182412821-41ceddba-b536-4a39-9985-7e171ab968fd.png)
Note that the first word sounds phonetically like what I typed, so maybe that's why it's proposed ?

And so on :
- « délicieuse » should already be shown at that stage, yet it's not and a lot of irrelevant words are shown :
![delicieuse-1](https://user-images.githubusercontent.com/5140169/182414314-b350701b-56fd-4b6a-a8cb-368a85e224b6.png)

- Three more letters have to by typed until at last the targeted word appears :
![delicieuse-2](https://user-images.githubusercontent.com/5140169/182415046-937cff25-4c3e-4329-879e-617d394a6af8.png)
![delicieuse-3](https://user-images.githubusercontent.com/5140169/182415087-7f0cc79d-d3ae-4bf6-b779-ac11303fe061.png)
![delicieuse-4](https://user-images.githubusercontent.com/5140169/182415111-f090b0c0-37f4-4973-adbf-9703d4d1d3ce.png)
And even then, it's only proposed as choice n°2, whereas choice n°1 is irrelevant here.

Is there a way to make it only propose words that are starting with the already typed letters ? It's as if it tries to correct what I already typed.

NB
In Vim/Deoplete it's better, probably because there is no corpus involved :
![boisson-vim](https://user-images.githubusercontent.com/5140169/182417530-7a52ce52-f3e7-4b28-91d2-dcbf8a37e9d0.png)
![delicieuse-vim](https://user-images.githubusercontent.com/5140169/182417545-e272c205-d7c8-4c6c-9f37-134807394a87.png)
![vim-delicieuse-](https://user-images.githubusercontent.com/5140169/182418471-a109bab0-7f61-4fad-abef-d5403e8bc582.png)

**Comment by bartekplus** [comment]
hey @benintech  the issue should be fixed in [2022.8.8](https://github.com/bartekplus/FluentTyper/releases/tag/2022.8.8).  The FluentTyper will still suggest some words that don't start with prefix you have typed, this is due how Aspell and Hunspell predictors are implemented. I've created another issue to track that https://github.com/bartekplus/FluentTyper/issues/4. I don't have any timeline if/when it will be fixed.
