### ISSUE TITLE
Add option "Suggest words only from Text Expander"

### ISSUE THREAD

**Issue by TotalCaesar659** [bartekplus/FluentTyper#30]
I often need to autocomplete only one word or phrase (or several ones), so I add them to Text Expander manually. But FluentTyper suggest other words from its dictionary, and it's very annoying. I propose to implement an option "Suggest words only from Text Expander" for this case.

**Comment by bartekplus** [comment]
Text Expander mode added in: 2023.1.3

**Comment by TotalCaesar659** [comment]
Thank you very much!
