### ISSUE TITLE
Auto-completes word on 'space' doesn't work when language is set to Text Expander

### ISSUE THREAD

**Issue by murko69** [bartekplus/FluentTyper#32]
Hi! Swedish user here that found this app really helpful. Sometimes I do actually need to write a lot in English (as now) but primary my language is Swedish and since that dictionary wasn't included I am trying the Text Expander feature.

..and under the tab text expander I have added a few words that I normally misspell in Swedish due to my finger settings and/or fingers being 'to fast'

I've added the shortcut 'itne' with the text 'inte' and teh shortcut 'kansek' with the text 'kanske'.
The shortcut is my usual spelling mistake and the text is the correct spelling.

Now when I misspell I can see the correct word coming up in the list, but it doesn't change it automatically when I hit space. I need to push enter or use the mouse - left click.

If I change the language settings to English it works fine (my two examples included) so I'm guessing the behavior with language Text Expander chosen is a bug?!

These are my settings!
![Screenshot(2)](https://user-images.githubusercontent.com/12071221/220328352-74179473-0a6a-4fb0-bbd3-4ec876b172ca.png)

Edit: put the image at the bottom

**Comment by murko69** [comment]
Sorry - Have to come crawling to the cross here!
I did a few browser restarts before I came calling the first time, since I'd heard about that beeing needed for some settings, but...

After computer needed restarting after a few updates earlier, I can actually and happily say that the feature is working as it should after hitting space bar even with prediction language set to Text Expander

I'll leave issue open for a while just to make sure it stays like this ;)

**Comment by bartekplus** [comment]
Starting from next release changes to  "Auto-completes word on 'space' " will work without need to reload page(or browser restart)
