### ISSUE TITLE
Doesn't work on Google

### ISSUE THREAD

**Issue by mamalion928** [bartekplus/FluentTyper#47]
Can't seem to get Fluent Typer to work on Google Docs or in the Google search engine.  Extension is toggled on, but no predictive text appears.
![image](https://user-images.githubusercontent.com/131992382/234917105-4f65e6d1-a4eb-459b-9f16-de60288c1785.png)

**Comment by bartekplus** [comment]
This is mentioned in the description that it won't work on Google docs.

It's a Google docs issue. Google Docs use canvas based rendering, which breaks extensions like FluentTyper. Only few extension are whitelisted, for those extensions Google docs use Html rendering.  I've tried to whitelist FT, but that's not possible for not very popular extension.

**Comment by sagarjaid** [comment]
> This is mentioned in the description that it won't work on Google docs.
> 
> It's a Google docs issue. Google Docs use canvas based rendering, which breaks extensions like FluentTyper. Only few extension are whitelisted, for those extensions Google docs use Html rendering. I've tried to whitelist FT, but that's not possible for not very popular extension.

That's so sad, I wonder why Google is doing this kind of rending.
