### ISSUE TITLE
Feature request: custom dictionary 

### ISSUE THREAD

**Issue by sarahjadesigns** [bartekplus/FluentTyper#48]
The Text Expander feature is really cool, but I wonder if this could be tweaked a bit or a similar feature could be implemented. Instead of (or in addition to being able to) essentially creating a shortcut to the expanded phrase (ex. asap = as soon as possible), you could just start typing the phrase and it would show up in the suggestions. Essentially this would be like adding multi-word terms to the dictionary.

I bring this up because I frequently need to type in full names (2 or 3 names with spaces between) that don't exist in the dictionary. And I have a fairly long list of them, too, so creating "shortcuts" in the current setup is impractical since it would be impossible to remember all of them.

**Comment by bartekplus** [comment]
Due to internal architecture of suggestion engine the `multi-word terms` functionality is not planed in near future.
