### ISSUE TITLE
Suggestion: allow export and import of Text Expander shortcuts

### ISSUE THREAD

**Issue by sarahjadesigns** [bartekplus/FluentTyper#49]
Apologies if this feature already exists, but I could not find an easy way to do it.

Import / export would allow the user to:

- create a backup of their shortcuts
- upload their shortcuts to secondary computers 
- do a batch upload of multiple shortcuts*

*Not sure if the current code format would allow for this. I'm just thinking something along the lines of being able to upload a .csv file from Excel or similar. If you want to create a lot of shortcuts from an existing list, for example, this would be much quicker than using the current form setup.

**Comment by bartekplus** [comment]
This functionality will be available in FluentTyper 2023.9.3
