### ISSUE TITLE
Feature request: Date today and time expander

### ISSUE THREAD

**Issue by dlazycoder** [bartekplus/FluentTyper#50]
when you type "today" it will show date today or time

**Comment by bartekplus** [comment]
Hey @dlazycoder, 

I started working on this feature. I've done some initial work,  currently I have two variables: 

- `date`  that expends to: `6/25/2023`
- `time` that expands to: `12:05:52 AM`

Could you share your use-cases and what variables would like to have supported?

**Comment by dlazycoder** [comment]
@bartekplus hello and thank you for your great work! I use date most of the time to help me with my work tool when filtering my outputs.

from what I am using it is `dtd` that expands to `2023/06/xx` I manually edit it according to the current month and the xx is manually edited when it is extended.

**Comment by bartosztomczyk** [comment]
Would the above format good for you?  M/D/YYYY vs YYYY/MM/DD?  

I use default date format for current language eg:

```
new Date().toLocaleDateString("en")
'6/27/2023'
new Date().toLocaleDateString("fr")
'27/06/2023'
```

**Comment by bartekplus** [comment]
@dlazycoder 
Would the above format good for you? M/D/YYYY vs YYYY/MM/DD?

I use default date format for current language eg:

```
new Date().toLocaleDateString("en")
'6/27/2023'
new Date().toLocaleDateString("fr")
'27/06/2023'
```

**Comment by bartekplus** [comment]
@dlazycoder 
I'll added custom time / date format, so you will be able to customize it according to your needs.  The code needs some more testing, I should be able to release it later this week.

**Comment by bartekplus** [comment]
@dlazycoder the `time` and `date` variables will be avialable in 2023.6.29. It's disabled by default (at least for now),  It can be enabled in  "Advanced" tab in FluentTyper settings.  `time` and `date` variables can be used in text expander e.g.:

`dtd` -> `Today is ${date}`

Also custom formatting can be specified so you should be able to customize it according to your needs. 

Please let me know if everything is working as expected!

**Comment by dlazycoder** [comment]
@bartekplus I just tried it now and it works like a charm! Huge thanks for your awesome work!
