### ISSUE TITLE
Bug: Long texts with line breaks does not expanding completely

### ISSUE THREAD

**Issue by dlazycoder** [bartekplus/FluentTyper#51]
for example if I assign this to text expander:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Maecenas sit amet elit sed urna convallis egestas et sit amet justo.
```

The output will be just

`Lorem ipsum dolor sit amet, consectetur adipiscing elit.`

**Comment by bartekplus** [comment]
Text expander was intended to work with as simple abbreviations expander. It’s more of input validation issue that multi line text are allowed. I’ll double check if multiline string are supported by https://github.com/bartekplus/presage

**Comment by bartekplus** [comment]
This has been fixed. Multiline text will work as expected now.
