### ISSUE TITLE
Doesn't work on rentry.org main text box

### ISSUE THREAD

**Issue by rynnil** [bartekplus/FluentTyper#53]
![image](https://github.com/bartekplus/FluentTyper/assets/67292233/1303aba7-c13f-404b-b78e-645e800129a7)

it does work on the bottom text box 
![image](https://github.com/bartekplus/FluentTyper/assets/67292233/efa7cd1c-9418-45b9-8d61-2a6e1ebacf6e)

**Comment by bartekplus** [comment]
I'll look into that next week

**Comment by bartekplus** [comment]
Fixed. Improved FluentTyper compatibility with some website like rentry.org
