### ISSUE TITLE
Multiple suggestion

### ISSUE THREAD

**Issue by PostmanU1** [bartekplus/FluentTyper#56]
Hi, sorry for my bad english, it's not a my native language. 
If my language isn't supported, but I'm using expander mode with mine words, could you make one amazing thing? When I added random word and his shortcut, it will be so helpful to make multiple word suggestion, like:
Shortcut: wI
Text:
1. when I will be
2. when I want to
3. wiem I need it

**Comment by bartekplus** [comment]
@PostmanU1 currently the text expander engine do not support multiple expansion with the same key. I'll look into that next, if this could be implemented without breaking other features.

**Comment by bartekplus** [comment]
@PostmanU1 This feature will available in next realease.
