### ISSUE TITLE
Data privacy question 

### ISSUE THREAD

**Issue by ritz84** [bartekplus/FluentTyper#59]
Hi, does this plugin extract information from the web page you are working on to the plugin servers at all? I work for a company as a transcriber and I'm looking for a software which can autocomplete words but does not extract any client information from my transcript or any other source on the web page. Thanks!

**Comment by bartekplus** [comment]
FluentTyper values the privacy of your data. It doesn't upload any of your data to the internet, and it works offline. Predictions are generated on your own PC.
