### ISSUE TITLE
Multiple words on this one trigger - help

### ISSUE THREAD

**Issue by PostmanU1** [bartekplus/FluentTyper#62]
Hello, I see the message of this new update for me, thank you for that. But I'm not so much technical, so I can't see any changes of this new version, updated by developer mode on Chrome, because I have nothing to update. So I check this line of codes of changes and I see, the parts of searching the same trigger for the used words isn't there in new version. But if I need to make this update manualy - I have no idea, how to do that or how to use it, this upgrade. Could you help?

**Comment by bartekplus** [comment]
You can see all releases and their change logs here: https://github.com/bartekplus/FluentTyper/releases

There is no release with mentioned functionality yet. I will be available in next release next week.

**Comment by PostmanU1** [comment]
Ou, thank you! I'm the new on github and so many options here. So i'm waiting for this, but glad to see this express response for the post.
