### ISSUE TITLE
Can Auto-complete on 'tab' be added as an option?

### ISSUE THREAD

**Issue by DustinReynoldsPE** [bartekplus/FluentTyper#63]
Love your work, but would appreciate the option of using a 'tab' to select the auto complete, if it is at all possible. Sometimes when I am trying to finish a word, I type space, but then that also auto completes the suggestion.  

Tab would let me specifically select the word that is being suggested, or to complete the partial word I'm on using a space.

Sorry if this is confusingly written :-)

**Comment by bartekplus** [comment]
@DustinReynoldsPE 

Auto complete on "space" is disabled by default (this can be enabled and disabled in options). And the auto complete using "Tab" is enabled by default, so you can select and complete words using "Tab" key.

Could you please elaborate more what the issue is about?

**Comment by DustinReynoldsPE** [comment]
@bartekplus Thanks for pointing out the obvious, I just tried it out and "Tab" works perfectly!  Thank you for the great addon!
