### ISSUE TITLE
minimum word length option for text expander

### ISSUE THREAD

**Issue by hyveplexel** [bartekplus/FluentTyper#65]
could there be an option to set minimum word length separately for the text expander?

**Comment by bartekplus** [comment]
hey, 

Such feature is not planed.  There are two cases to consider here:

- When "language" is selected, then internal prediction module do not allow to have different "min word length" for different data source. I wouldn't like to do that :)
- When "textExpander" only mode is used, then you can select "min word length", but it will be applied to all languages. Per language settings are not planed as this make configuration initiative and confusing for users.
