### ISSUE TITLE
Suggestion: Rebindable auto complete key(s)

### ISSUE THREAD

**Issue by dEATh-PM** [bartekplus/FluentTyper#69]
Personally, I'd prefer the Tab key to auto complete, as per Visual Studio to name one.
But then thinking on I realized that people have all kinds of custom keyboards and disabilities, rather than adding one more option perhaps the more future-proof solution is to make a listen-capture type function that allows for N-number of ways to auto complete.

I don't know that this is possible in the framework.

**Comment by bartekplus** [comment]
I wouldn't like to add that. Currently, you can use "Tab," which is enabled by default, and "Space" or "Enter," which can be enabled in options. Introducing more keys or allowing customization could create more issues than it solves. Many other keys, such as Ctrl, Shift, and Alt, already have special meanings, such as typing emotes or diacritic characters. Given the lack of significant demand, I wouldn't like  invest time in implementing this feature.

PS. please not that that some pages captures key events before this extension has chance to grab them, and sometime "tab"  will not work, or "enter" key will jump to new line. There is no way to fix that.

**Comment by dEATh-PM** [comment]
I didn't even test "Tab" as it wasn't listed, I guess that's on me.
