### ISSUE TITLE
Bug: First letter decapitation after non letter character

### ISSUE THREAD

**Issue by dEATh-PM** [bartekplus/FluentTyper#71]
When auto completing a word preceded by a non letter character, the first letter will be turned into a lowercase character.
The prime examples being quotation sign " and asterisk *.

![image](https://github.com/bartekplus/FluentTyper/assets/150959192/10cec47a-08b4-49c8-814e-2138f1297a13)

**Comment by dEATh-PM** [comment]
I just posted a bunch of "issues" I hope that's OK.
I've been using the extension for Firefox (I don't know if it's available on any other browser) for about a month and I get a lot of use out of it, so I hope I don't come off as complaining, I just wish for awesome to be awesomer.

**Comment by bartekplus** [comment]
I'll try to look into that in upcoming days.
