### ISSUE TITLE
All my expands were gone after the recent update 

### ISSUE THREAD

**Issue by dlazycoder** [bartekplus/FluentTyper#74]
https://imgur.com/a/0d2GCuk

Just today, Dec.18th. I found out that all my expands are gone.

**Comment by bartekplus** [comment]
What version are you at ? And what browser?

In new extension I switched to local storage, but there is a migration build it. I just tested the 2023.09.30(from Firefox add ons website) added few expands, then updated to 2023.12.15.1 and all of the were successfully migrated. Sorry it didn't work for you. As a workaround you could install old version, export your expansions then update to new one and import them.

**Comment by dlazycoder** [comment]
I'm using 2023.12.15.1 version.
I managed to have a back up of my expands since I have another PC that was synced to it, glad it was not updated there.

**Comment by murko69** [comment]
Sadly I just noticed the same thing. Settings and my complete library of Text Extender is set to default mode and all my added words are gone,
Sadly I never made a backup (CSV) of it :/

Firefox
FT version 2023.12.15.1

**Comment by murko69** [comment]
> I'm using 2023.12.15.1 version. I managed to have a back up of my expands since I have another PC that was synced to it, glad it was not updated there.

Thanks for that tip. I have the same setup and managed to get a backup from another computer at home that wasn't yet updated to newer version!

**Comment by bartekplus** [comment]
I double checked on two other computers. Firefox on Linux and Firefox on MacOs. It worked like a charm without any issues. The configuration was correctly migrated when updating extension from 2023.09.30  to 2023.12.15.1.  
What Firefox version and OS are using? Do you know if there was Firefox FluentTyper update at the same time ?

**Comment by murko69** [comment]
On the computer with the newer FluentTyper (the one that suddenly went default mode) I have Firefox 120.0.1 (64-bit) running on Win 10!
And my add-ons are automatically updated on that one so I don't know when the update was made.
But because that computer was on service for 3 weeks I don't know if some version of FT was skipped in the process or not.

**Comment by murko69** [comment]
I just tried going back to 2023.09.30 but the expands was still gone.
Managed to fix it with the exported CSV from the other computer. Still.... My old settings are still in default mode like Language and domain list mode (including my whitelist), but since I just use the add-on on a handful of pages that's an easier fix to make.

**Comment by bartekplus** [comment]
@murko69 @dlazycoder Can any of you perform a test by downgrading to version 2023.09.30, adding some text expands, and then updating to version 2023.12.15.1 ? I am unable to reproduce the issue locally. Unless someone is willing to invest time in debugging, it may remain unresolved. 

@murko69 Feel free to open feature request or prepare pull request.

**Comment by bartekplus** [comment]
I've added alternative migration mechanism to avoid such issues for other users.
@murko69 @dlazycoder  there could be another update issue for you guys, sorry for that. The 2023.12.19 will migrate setting once again for you(and it might overtires your local changes)

**Comment by murko69** [comment]
Thanks for the heads up @bartekplus. 
I'm on the road (working) right now and can't test anything from this device regarding your two last posts.
Back home in a few days.
