### ISSUE TITLE
[FRENCH]aujourd'hui

### ISSUE THREAD

**Issue by benintech** [bartekplus/FluentTyper#8]
We talk a lot about quotes in my issues. A little explanation is maybe in order. « L' » is an article, like « the » in English :
Un avion = A plane
L'avion = The plane

« L' » is the only article using a single quote. It's the equivalent of « the » in English, and is used when the following word starts with a vowel : « L'avion », « L'Amérique », and so on. When the word starts with a consonant we use « le » ou « la », e.g. « Le chien » (The dog), « La maison » (The house), ...

Like I already mentioned in [issue#2](https://github.com/bartekplus/FluentTyper/issues/2), there are a very few words in which a single quote is part of the word. Only 3 examples come to my mind : « prud'hommes », « ad'hoc » and « aujourd'hui ».  You _could_ safely ignore those words if it's too cumbersome to take them into account, but note however that the word « aujourd'hui » is **very frequently** used (it means « today »).

In FT there is a mistake, it proposes the word « aujourdhui » (without quote), which doesn't exist :
![aujourdhui](https://user-images.githubusercontent.com/5140169/183632815-cf428a69-e4c4-4077-a44c-34e7d539fa9b.png)

The right behavior should be :
![aujourdhui-vim](https://user-images.githubusercontent.com/5140169/183633008-77f547a0-7665-44e9-8461-a38220050050.png)

**Comment by bartekplus** [comment]
This is caused by french corpus database used by n-gram predictor. It is   databases of sentences from random internet sources. There could be typos/errors in those sentenced that I cannot spot and fix. I will run hunspell over the database to exclude misspelled word, it should fix the issue.
