### ISSUE TITLE
Textexpander imports disappears

### ISSUE THREAD

**Issue by anoukmulder** [bartekplus/FluentTyper#80]
I have to re-import the csv for the textexpander every time I restart my browser (firefox for OSX).
Is there a way to save the import?

**Comment by bartekplus** [comment]
@anoukmulder 
I just tested the newest version available (2023.12.19) on Firefox for OSX, and it works fine for me. The imported text expansions from CSV are stored correctly and remain after a browser restart.

What versions of FluentTyper and Firefox are you using? Can you try removing and reinstalling FluentTyper? Additionally, could you please provide the CSV file you are importing that shows this issue?

**Comment by bartekplus** [comment]
@anoukmulder any update?

**Comment by bartekplus** [comment]
Please reopen the issue if you are still experiencing it and provide additional information.
