### ISSUE TITLE
Add support for Brazilian Portuguese language 

### ISSUE THREAD

**Issue by natanbalthazar** [bartekplus/FluentTyper#83]
Hi, it is possible to add support for Brazilian Portuguese language?

**Comment by bartekplus** [comment]
Hi @natanbalthazar! I appreciate your interest in Brazilian Portuguese support. If there's more demand for it, I'll consider adding the language. Due to time constraints, the earliest I can work on this is in March. Thank you for understanding

**Comment by natanbalthazar** [comment]
Goodnight friend @bartekplus! Thanks for the answer. I understand that it is not possible to do it now, and that is okay. In that case, is there anything I could help you with to speed up the process?

Regarding demand, I'm waiting for this update in Brazilian Portuguese to announce this extension to some friends.

Furthermore, I thought the idea was sensational, I could even say unique, and I wish it success!

**Comment by natanbalthazar** [comment]
I understood. I would like to help, but, unfortunately, I don't even know where to start. So, I look forward to this new feature.

**Comment by K0R0B0R0S** [comment]
Brazilian portugues would be nice

**Comment by lucsoliveira** [comment]
I agree with guys above.

**Comment by natanbalthazar** [comment]
Thank you my friend @bartekplus!

**Comment by natanbalthazar** [comment]
What's up friend @bartekplus, how are you?

I saw that you added the Brazilian Portuguese language among the possible languages to be used in the extension and I am very grateful for that.

However, I still cannot view/select it from the list. Could you tell me why?

Sorry for the inconvenience and thanks in advance.

This image is from today after downloading the extension again as a test on Google Chrome for Windows.

![image](https://github.com/bartekplus/FluentTyper/assets/62712246/8047cead-fa46-4b1c-8962-db1fa5aa1773)

**Comment by bartekplus** [comment]
Did you check version of the extension? 

It takes few days few to accept new version in Chrome webstore.
