### ISSUE TITLE
The extension sometimes stop working on chromium browser.

### ISSUE THREAD

**Issue by riskirills66** [bartekplus/FluentTyper#84]
I tried other browsers like Edge and Chrome. The FluentTyper often goes missing and doesn't work without a browser restart. However, when I try it on Firefox, it always works.

**Comment by bartekplus** [comment]
I'm unable to reproduce it. I need more input from you, such as the version of your operating system, browser, and extension, along with the reproduction steps. Without this information, I cannot take any action to address the issue

**Comment by riskirills66** [comment]
I use Microsoft Edge
Version 121.0.2277.83 (Official build) (64-bit)
Windows 10
![image](https://github.com/bartekplus/FluentTyper/assets/60280769/7d9f1f73-fec0-4224-b226-e9f219567687)

**Comment by bartekplus** [comment]
@riskirills66 And what are the reproduction steps ? I tested it on latest Edge and didn't notice any issues.

**Comment by bartekplus** [comment]
Closing. User feedback missing.
