### ISSUE TITLE
Feature request: Show also entries that start with typed letters

### ISSUE THREAD

**Issue by dand751801** [bartekplus/FluentTyper#86]
Is it possible to show entries that start with typing, too, instead of just showing the direct matches?

For example: 
I created the following abbreviations:
zw = zwischen
zwi = Zwinglistr.
zwi = Zwinglistraße

![grafik](https://github.com/bartekplus/FluentTyper/assets/60128881/1a45ac36-c097-4d88-9149-214a4055f396)

When I type "z" no suggestion appears at all (even though I set input length to 1 character). What did I wrong?
When entering "zw" only "zwischen" is suggested, but not "Zwinglistr." and “Zwinglistrasse”.
I think it would be great if all 3 options were displayed at "z" and "zw".

I'm using:
- Mozilla Firefox 115.4 ESR
- FluentTyper 2024.1.12

**Comment by bartekplus** [comment]
@dand751801 You are trying to abuse feautee for things it was not designed for.
