### ISSUE TITLE
Automatically detecting language is only partially functional. 

### ISSUE THREAD

**Issue by gotonickpappas** [bartekplus/FluentTyper#89]
The auto detection sometimes works but most of the time it does not. I was not able to understand why sometimes it does work... 
I am attaching some pics that illustrate the issue. Basically, if you are typing in English and you switch to Greek (whether that is in the middle of a sentence or you start a new sentence) then if you are using space for filling suggestions, it results in a bunch of Α Α Α Α, (Αλφά) if you had started with Greek and switched to English, or a bunch of W W W W if you had started typing in English and you switched to Greek. 

Often the entire thing stops working for reasons that I could not firmly establish. Reloading a page seems to resolve the issue. 
If you start with English this happens if you switch to Greek:
![Screenshot 2024-02-18 110750](https://github.com/bartekplus/FluentTyper/assets/18703679/1f989b6f-2c29-47e7-943e-9ea660e7a5e0)

If you start with Greek this is what happens if you switch to English:
![Screenshot 2024-02-18 111450](https://github.com/bartekplus/FluentTyper/assets/18703679/7a443aad-6264-43c6-8886-3f00e29e8863)

When sometimes the entire thing stops working:
<img width="433" alt="image" src="https://github.com/bartekplus/FluentTyper/assets/18703679/ad05012e-ae76-46bb-be4f-640ece1a276c">

After you reload the page:
![Screenshot 2024-02-18 112158](https://github.com/bartekplus/FluentTyper/assets/18703679/42f47cce-ffc0-4a63-9b00-9b0f87d5c13e)

**Comment by bartekplus** [comment]
The language detection works in the following way:

 - It takes input text and calls the browser's native API to detect language (chrome.i18n.detectLanguage).
    - If the language is detected and supported by the extension, it is used to predict words.
 - If the language detection fails, it tries to detect the page language and uses that.
 - If both of the above fail, it resorts to using the fallback configured language.

Switching language mid-sentence is not well supported by the API (e.g., if the API suggests with 90% probability that the language is English and with 20% it's Greek, the extension will use the most probable option, which aligns with what 99% of users would expect). In the past, I experimented with limiting the text passed to the API to switch earlier, but the results were not very stable and  not predictable(much worse then it is now ).

Therefore, unless language detection improves in browsers, I do not plan to implement language detection in the extension itself.

Regarding the issue where FF stops working, please open a separate issue for it with clear steps to reproduce
