### ISSUE TITLE
Provide option to enable / disable any key  as a auto-completion trigger (2)  provide option to disable 'tab'

### ISSUE THREAD

**Issue by nausher** [bartekplus/FluentTyper#90]
Currently, 'tab' is a auto-completion trigger but there's no way to disable it, unlike there are options in the settings for 'spacebar' and 'enter'. This could be an option, additionally,  if the options could provide the ability to choose the auto-completion trigger that would be great.

![image](https://github.com/bartekplus/FluentTyper/assets/79359/a1effa89-9e0f-4ad0-9bd9-cd928628965a)

**Comment by nausher** [comment]
The primary reason to request this is that the 'tab' key is used by other completion  systems like Gmail and Google's auto-complete feature.

**Comment by bartekplus** [comment]
I'll take a look into that, but there's no timeline for implementing this feature.

**Comment by bartekplus** [comment]
Option to disable "Tab" will be added in next version./

**Comment by nausher** [comment]
Thank you! I see the feature has been launched.
