### ISSUE TITLE
Hotkey to trigger auto complete pop-up extension 

### ISSUE THREAD

**Issue by nausher** [bartekplus/FluentTyper#92]
Currently the pop-up is triggered solely based on the number of letters typed.
Can an option be provided for a hotkey that triggers auto-completion? 

The auto-completion need not be triggered until the user presses the specific hot-key?
E.g. option + .  can be used to trigger the auto-complexity.  This will help from having the extension getting in the way. 
and can also help improve performance by not making as many calls to the service.

**Comment by bartekplus** [comment]
I'll take a look into that, but there's no timeline for implementing this feature.

**Comment by bartekplus** [comment]
This will be included in next version, pop-up can be triggered by key shortcut.  Extension can also be set to work only in manual trigger mode by using `-1` as  `minimum word length`

> This setting determines the minimum word length required to trigger the prediction feature.
> If set to '0', predictions will appear after a whitespace.
> If set to '-1', predictions must be triggered manually using a key shortcut.
> Default shortcut: Ctrl+Period. To change, consult your browser's help section ([Firefox](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox), [Chrome](chrome://extensions/shortcuts)). Please note that some key combinations may not work.

**Comment by nausher** [comment]
Thanks for making these changes!
